# Generated by Django 4.0.1 on 2022-02-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_address_event_mobile_event_pin_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='address',
            new_name='req_mobile',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pin_code',
        ),
    ]
