services:
  backend:
    build: Backend/
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
  
  frontend:
    build: Frontend/
    command: ["python", "-m", "http.server", "8080"]
    ports:
      - "8080:8080"
  