openapi: 3.0.1
info:
  title: Event Managment System
  description: This is a sample API Docs for Event Managment System (eventMsys)
  contact:
    email: keshav.sharma@yesavail.digital
  version: 1.0.0
servers:
- url: http://localhost:8000/
tags:
- name: Event
  description: Everything about your Events
- name: Payments
  description: All about checkout, order and payments
paths:
  /apis/events:
    get:
      tags:
      - Event
      summary: Check Events
      description: Check the All avaialble events
      operationId: events
      parameters:
      - name: format
        in: query
        description: To Get json format
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successful operation
          content: {}
        400:
          description: Invalid status value
          content: {}
  /apis/event/{eventPK}:
    get:
      tags:
      - Event
      summary: Get the Date of particular Event
      description: Returns a Dates registered for that Event
      operationId: geteventById
      parameters:
      - name: eventPK
        in: path
        description: ID of Event to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content: {}
        400:
          description: Invalid ID supplied
          content: {}
  /payment/checkout:
    post:
      tags:
      - Payments
      summary: Send data to create Order
      operationId: createorder
      responses:
        200:
          description: successful operation
          content: {}
  /payment/checkin:
    post:
      tags:
      - Payments
      summary: Send data to Mark Order paid or Not paid
      operationId: updateorder
      responses:
        200:
          description: successful operation
          content: {}
components: {}
