# Generated by Django 4.0.1 on 2022-02-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='pytmcheck',
            field=models.CharField(default='', max_length=250),
        ),
    ]
