# Generated by Django 4.0.1 on 2022-02-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_checkout_address_alter_checkout_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='pytmcheck',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='pin_code',
            field=models.IntegerField(null=True),
        ),
    ]
