# Generated by Django 4.0.1 on 2022-02-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_req_email_event_req_name'),
        ('payments', '0004_remove_checkout_pytmcheck_alter_checkout_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
